const products = [
    {
        id: 1, 
        titulo: "LEGO Star Wars: Skywalker Saga", 
        categoria: "Juegos",
        precio: 30,
        descripcion: "La galaxia es tuya con LEGO® Star Wars™: La Saga Skywalker. Vive los momentos inolvidables y llenos de acción de las nueve películas de la saga a través del humor característico que ofrece LEGO",
        reseñas: "+33k Muy Positivas",
        fecha: "5 ABR 2022",
        desarrollador: "TT Games",
        imagen: "/src/assets/products_img/legostarwars.jpg",
    },
    { 
        id: 2, 
        titulo: "ELDEN RING",
        categoria: "Juegos",
        precio: 50,
        descripcion: "Un vasto mundo perfectamente conectado en el que los territorios abiertos estarán repletos de situaciones y mazmorras enormes. Mientras exploras, experimentarás el deleite de descubrir amenazas desconocidas y sobrecogedoras junto una historia muy profunda contada en fragmentos. Un drama épico en el que las motivaciones de cada personaje se encuentran en las Tierras Intermedias.",
        reseñas: "+600k Muy Positivas",
        fecha: "24 FEB 2022",
        desarrollador: "FromSoftware Inc",
        imagen: "/src/assets/products_img/eldenring.jpg",
    },
    { 
        id: 3, 
        titulo: "DRAGON BALL Z: KAKAROT",
        categoria: "Juegos",
        precio: 50,
        descripcion: "¡Revive la historia de Son Goku y otros Guerreros Z en DRAGON BALL Z: KAKAROT! Conoce el mundo de DRAGON BALL Z no solo por sus épicos combates, sino también mientras luchas, pescas, comes y entrenas con Son Goku, Son Gohan, Vegeta y muchos más.",
        reseñas: "+37k Muy Positivas",
        fecha: "16 ENE 2020",
        desarrollador: "CyberConnect2",
        imagen: "/src/assets/products_img/dbkakarot.jpg",
    },
    { 
        id: 4, 
        titulo: "Grand Theft Auto V: Edición Premium",
        categoria: "Juegos",
        precio: 30,
        descripcion: "Cuando un joven estafador callejero, un ladrón de bancos retirado y un psicópata aterrador se ven involucrados con lo peor y más desquiciado del mundo criminal, del gobierno de los EE. UU. y de la industria del espectáculo, tendrán que llevar a cabo una serie de peligrosos golpes para sobrevivir en una ciudad implacable en la que no pueden confiar en nadie. Y mucho menos los unos en los otros.",
        reseñas: "+1.6M Muy Positivas",
        fecha: "14 ABR 2015",
        desarrollador: "Rockstar Games",
        imagen: "/src/assets/products_img/gta5.jpg",
    },
    { 
        id: 5, 
        titulo: "Red Dead Redemption 2",
        categoria: "Juegos",
        precio: 60,
        descripcion: "America, 1899. Arthur Morgan y la banda de Van der Linde se ven obligados a huir. Con agentes federales y los mejores cazarrecompensas de la nación pisándoles los talones, la banda deberá atracar, robar y luchar para sobrevivir en su camino por el escabroso territorio del corazón de América. Mientras las divisiones internas aumentan y amenazan con separarlos a todos, Arthur deberá elegir entre sus propios ideales y la lealtad a la banda que lo vio crecer.",
        reseñas: "+500k Muy Positivas",
        fecha: "5 DIC 2019",
        desarrollador: "Rockstar Games",
        imagen: "/src/assets/products_img/rdr2.jpg",
    },
    { 
        id: 6, 
        titulo: "Poppy Playtime - Chapter 3",
        categoria: "Juegos",
        precio: 10,
        descripcion: "Un orfanato en ruinas, conocido como la Guardería, se ubica bajo lo que fuera una fábrica de juguetes mágicos. Debes atravesar este lugar embrujado, resolver nuevos desafíos y evitar las pesadillas que acechan en la oscuridad. Las respuestas yacen entre las sábanas ensangrentadas y el eco de los gritos... Si puedes sobrevivir.",
        reseñas: "+6k Muy Positivas",
        fecha: "30 ENE 2024",
        desarrollador: "Mob Entertainment",
        imagen: "/src/assets/products_img/ppt3.jpg",
    },
    { 
        id: 7, 
        titulo: "Steam Tarjeta de Regalo USD$5",
        categoria: "GiftCard",
        precio: 5,
        descripcion: "Las tarjetas regalo de Steam funcionan como vales que pueden canjearse para adquirir juegos, software, hardware o cualquier otro artículo disponible en Steam.",
        reseñas: "-",
        fecha: "-",
        desarrollador: "Steam",
        imagen: "/src/assets/products_img/steam5.png",
    },
    { 
        id: 8, 
        titulo: "Steam Tarjeta de Regalo USD$10",
        categoria: "GiftCard",
        precio: 10,
        descripcion: "Las tarjetas regalo de Steam funcionan como vales que pueden canjearse para adquirir juegos, software, hardware o cualquier otro artículo disponible en Steam.",
        reseñas: "-",
        fecha: "-",
        desarrollador: "Steam",
        imagen: "/src/assets/products_img/steam10.png",
    },
    { 
        id: 9, 
        titulo: "Steam Tarjeta de Regalo USD$25",
        categoria: "GiftCard",
        precio: 25,
        descripcion: "Las tarjetas regalo de Steam funcionan como vales que pueden canjearse para adquirir juegos, software, hardware o cualquier otro artículo disponible en Steam.",
        reseñas: "-",
        fecha: "-",
        desarrollador: "Steam",
        imagen: "/src/assets/products_img/steam25.png",
    },
    { 
        id: 10, 
        titulo: "Steam Tarjeta de Regalo USD$50",
        categoria: "GiftCard",
        precio: 50,
        descripcion: "Las tarjetas regalo de Steam funcionan como vales que pueden canjearse para adquirir juegos, software, hardware o cualquier otro artículo disponible en Steam.",
        reseñas: "-",
        fecha: "-",
        desarrollador: "Steam",
        imagen: "/src/assets/products_img/steam50.png",
    },
    { 
        id: 11, 
        titulo: "Steam 1 Random Grand Key",
        categoria: "RandomKeys",
        precio: 4,
        descripcion: "Deja que el destino decida que juego vas a experimentar, obtendras 1 SteamKey aleatoria de un juego Grand",
        reseñas: "-",
        fecha: "-",
        desarrollador: "Plataforma Steam",
        imagen: "/src/assets/products_img/grand1.png",
    },
    { 
        id: 12, 
        titulo: "Steam 5 Random VIP Keys",
        categoria: "RandomKeys",
        precio: 6,
        descripcion: "Deja que el destino decida que 5 juegos vas a experimentar, obtendras 5 SteamKeys aleatorias con juegos VIP",
        reseñas: "-",
        fecha: "-",
        desarrollador: "Plataforma Steam",
        imagen: "/src/assets/products_img/vip5.png",
    },
    { 
        id: 13, 
        titulo: "Steam 5 Random Diamond Keys",
        categoria: "RandomKeys",
        precio: 5,
        descripcion: "Deja que el destino decida que 5 juegos vas a experimentar, obtendras 5 SteamKeys aleatorias con juegos Diamond",
        reseñas: "-",
        fecha: "-",
        desarrollador: "Plataforma Steam",
        imagen: "/src/assets/products_img/diamond5.png",
    },
    { 
        id: 14, 
        titulo: "Steam 5 Random Elite Keys",
        categoria: "RandomKeys",
        precio: 8,
        descripcion: "Deja que el destino decida que 5 juegos vas a experimentar, obtendras 5 SteamKeys aleatorias con juegos Elite",
        reseñas: "-",
        fecha: "-",
        desarrollador: "Plataforma Steam",
        imagen: "/src/assets/products_img/elite5.png",
    },
];

export const getProducts = new Promise((resolve) => {
    resolve(products)
})

export const getProductId = (id) => {
    return products.find((prod) => prod.id == id)
}

export const getProductCategory = (categoria) => {
    return products.find((prod) => prod.categoria == categoria)
}